#assurance_rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: assurance-rolebinding
subjects:
- kind: ServiceAccount
  name: assurance-sa
  namespace: sagin-network
roleRef:
  kind: ClusterRole
  name: assurance-role
  apiGroup: rbac.authorization.k8s.io

