#assurance_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assurance-role
rules:
- apiGroups: [""]
  resources:
    - pods
  verbs:
    - get
    - list
    - watch

