# drl_agent/drl_agent_clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drl-agent-rolebinding
subjects:
- kind: ServiceAccount
  name: drl-agent-sa
  namespace: sagin-network
roleRef:
  kind: ClusterRole
  name: drl-agent-role
  apiGroup: rbac.authorization.k8s.io
