# llm_translation_engine/llm_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-translation-engine
  namespace: sagin-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-translation-engine
  template:
    metadata:
      labels:
        app: llm-translation-engine
    spec:
      # hostNetwork: true  # Enable host networking
      containers:
      - name: llm-translation-engine
        image: llm_translation_engine:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
